INSERT INTO "USERS" (ID, NAME, EMAIL, CREATED_AT, UPDATED_AT) VALUES (1, '홍길동', 'hong@test.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "USERS" (ID, NAME, EMAIL, CREATED_AT, UPDATED_AT) VALUES (2, '김철수', 'kim@test.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
