INSERT INTO "USERS" (ID, NAME, EMAIL, CREATED_AT, UPDATED_AT) VALUES (1, '홍길동', 'hong@test.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "USERS" (ID, NAME, EMAIL, CREATED_AT, UPDATED_AT) VALUES (2, '김철수', 'kim@test.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO "PAYMENTS" (ID, ORDER_ID, CAPTURE_ID, CAPTURE_HREF, USER_ID, AMOUNT, CURRENCY, STATUS) VALUES (1, 'AQWS!23', '', '', 1, 100.00, 'USD', 'CREATED')
